### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Kyedae** [kry0sc0pic/cypher#1]
May i either contact you on discord or can you help me here? i tried starting the bot, after setting up the env and i get this, I've added you on discord btw.
![image](https://user-images.githubusercontent.com/85193207/174793264-e7560154-349e-498c-a8ce-c0c3be2865ee.png)

**Comment by kry0sc0pic** [comment]
Hi,

sorry for the late response :)

You can send me a friend request on discord:
Kry0#1327


I can help you further there


EDIT:
-  I haven't got any friend requests

**Comment by kry0sc0pic** [comment]
Can u clone the `fix/#1` branch of the repo and try running it. If you run into the same issues let me know :)

**Comment by Kyedae** [comment]
My apologies, didnt know you replied! that seems to work, but my issue i think is im not sure how to set up the supabase database? can u show me how to? also i've added u on discord but im guessing u dont see it, and how would i make it auto add users that add the bot?

**Comment by kry0sc0pic** [comment]
Error was caused because supabase was not setup, closing.
